### ISSUE TITLE
[Bug]: Runtime error on importing ivy

### ISSUE THREAD

**Issue by nikifaets** [unifyai/ivy#10622]
### Bug Explanation

Ivy cannot be imported due to runtime error coming from `ast_helpers.py`. I believe it has been introduced in this PR:  https://github.com/unifyai/ivy/pull/10327

### Steps to Reproduce Bug

Code to reproduce:

```
>>> import ivy
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/nikifaets/code/ivy/ivy/exceptions.py", line 41, in _custom_exception_handle
    trace_mode = ivy.get_exception_trace_mode()
AttributeError: module 'ivy' has no attribute 'get_exception_trace_mode'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikifaets/code/ivy/ivy/__init__.py", line 708, in <module>
    from ivy.utils.backend import (
  File "/home/nikifaets/code/ivy/ivy/utils/__init__.py", line 2, in <module>
    from . import backend
  File "/home/nikifaets/code/ivy/ivy/utils/backend/__init__.py", line 2, in <module>
    from . import handler
  File "/home/nikifaets/code/ivy/ivy/utils/backend/handler.py", line 12, in <module>
    from ivy.utils.backend import ast_helpers
  File "/home/nikifaets/code/ivy/ivy/utils/backend/ast_helpers.py", line 32, in <module>
    local_modules = _retrive_local_modules()
  File "/home/nikifaets/code/ivy/ivy/utils/backend/ast_helpers.py", line 21, in _retrive_local_modules
    for entry in os.scandir(wd):
FileNotFoundError: [Errno 2] No such file or directory: ''
```

When running the Python interpreter from a virtual env, outside dev docker container:
- I observe this is only happens when starting a Python interpreter from the project root folder, `ivy/`.
- It imports fine when I run the interpreter from an arbitrary other directory, e.g. `/home`, `ivy/ivy`, `ivy/ivy/utils`.

When I run the Python interpreter inside the Ivy dev container:
- The error is hit no matter in which directory I open the Python interpreter

### Environment

Linux, Dev Container, conda environment

### Ivy Version

1.1.9

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

**Comment by CatB1t** [comment]
Hello @nikifaets, thank you for taking the time to report the issue! fixed in https://github.com/unifyai/ivy/commit/19eabcb460007aa89bd6f934ccc7c5714b2ecad7
