### ISSUE TITLE
Unit-Test Error

### ISSUE THREAD

**Issue by Sarvesh-Kesharwani** [unifyai/ivy#12355]
/usr/bin/python3 /ivy/main.py 
Error in sys.excepthook:
Traceback (most recent call last):
  File "/ivy/ivy/utils/exceptions.py", line 41, in _custom_exception_handle
    trace_mode = ivy.get_exception_trace_mode()
AttributeError: module 'ivy' has no attribute 'get_exception_trace_mode'

Original exception was:
Traceback (most recent call last):
  File "/ivy/main.py", line 1, in <module>
    import ivy
  File "/ivy/ivy/__init__.py", line 714, in <module>
    from . import functional
  File "/ivy/ivy/functional/__init__.py", line 1, in <module>
    from .ivy import experimental
  File "/ivy/ivy/functional/ivy/__init__.py", line 10, in <module>
    from . import device
  File "/ivy/ivy/functional/ivy/device.py", line 9, in <module>
    import pynvml
ModuleNotFoundError: No module named 'pynvml'

Process finished with exit code 1

**Comment by Sarvesh-Kesharwani** [comment]
Solution steps to follow to fix the issue:-
1)
2)
3)
.....
