### ISSUE TITLE
Quick start code is not working after recent update.

### ISSUE THREAD

**Issue by someshfengde** [unifyai/ivy#2145]
quickstart code: 
```
import ivy

class MyModel(ivy.Module):
    def __init__(self):
        self.linear0 = ivy.Linear(3, 64)
        self.linear1 = ivy.Linear(64, 1)
        ivy.Module.__init__(self)

    def _forward(self, x):
        x = ivy.relu(self.linear0(x))
        return ivy.sigmoid(self.linear1(x))

ivy.set_backend('torch')  # change to any backend!
model = MyModel()
optimizer = ivy.Adam(1e-4)
x_in = ivy.array([1., 2., 3.])
target = ivy.array([0.])

def loss_fn(v):
    out = model(x_in, v=v)
    return ivy.mean((out - target)**2)

for step in range(100):
    loss, grads = ivy.execute_with_gradients(loss_fn, model.v)
    model.v = optimizer.step(model.v, grads)
    print('step {} loss {}'.format(step, ivy.to_numpy(loss).item()))

print('Finished training!')

```

error I am getting 

```
b2ca9801389c:python3 -u /ivy/ivy/functional/ivy/sample_file.py
Traceback (most recent call last):
  File "/ivy/ivy/functional/ivy/sample_file.py", line 24, in <module>
    loss, grads = ivy.execute_with_gradients(loss_fn, model.v)
  File "/ivy/ivy/func_wrapper.py", line 323, in new_fn
    return cont_fn(*args, **kwargs)
  File "/ivy/ivy/container/gradients.py", line 157, in static_execute_with_gradients
    return ContainerBase.multi_map_in_static_method(
  File "/ivy/ivy/container/base.py", line 198, in multi_map_in_static_method
    ret = ivy.Container.multi_map(
  File "/ivy/ivy/container/base.py", line 674, in multi_map
    ret = ivy.Container.multi_map(
  File "/ivy/ivy/container/base.py", line 701, in multi_map
    return_dict[key] = func(values, this_key_chain)
  File "/ivy/ivy/container/base.py", line 193, in map_fn
    return fn(*a, **kw)
  File "/ivy/ivy/func_wrapper.py", line 327, in new_fn
    return fn(*args, **kwargs)
  File "/ivy/ivy/func_wrapper.py", line 96, in new_fn
    return fn(*new_args, **new_kwargs)
  File "/ivy/ivy/func_wrapper.py", line 152, in new_fn
    ret = fn(*args, **kwargs)
  File "/ivy/ivy/functional/backends/torch/gradients.py", line 27, in execute_with_gradients
    func_ret = func(xs)
  File "/ivy/ivy/functional/ivy/sample_file.py", line 20, in loss_fn
    out = model(x_in, v=v)
  File "/ivy/ivy/stateful/module.py", line 659, in __call__
    ret = self._call(*args, v=v, with_grads=with_grads, **kwargs)
  File "/ivy/ivy/stateful/module.py", line 375, in _call
    Container(v, **v.config) if isinstance(v, Container) else Container(v)
  File "/ivy/ivy/container/container.py", line 69, in __init__
    ContainerBase.__init__(
  File "/ivy/ivy/container/base.py", line 151, in __init__
    self.inplace_update(dict_in, **self._config_in)
  File "/ivy/ivy/container/base.py", line 1507, in inplace_update
    raise Exception("invalid input {}".format(dict_in))
Exception: invalid input tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)

Process finished with exit code 1

```

Code is ran with docker configured in pycharm.

**Comment by jkeane508** [comment]
Hi 👋

I've just ran your code on my locally and it is not throwing any errors. Can you please ensure you have the latest version of Ivy Master Branch from the GitHub Repository and try running it again. 😀

Thanks!

**Comment by someshfengde** [comment]
Sorry for not updating here @juliagsy  updated the function code for solving the container issue. 
Now it's working how it's supposed to be 

btw thanks for your reply @jkeane508  :smile:
