### ISSUE TITLE
[Bug]Deprecated `np.float` Usage Causes AttributeError in check_float Function

### ISSUE THREAD

**Issue by akshatvishu** [unifyai/ivy#21853]
### Bug Explanation

This problem was first highlighted by @ozogxyz  at this [message](https://discord.com/channels/799879767196958751/1000043749088436315/1140673955787706379) in the discord server.

In the `check_float` function within the `ivy/functional/ivy/data_type.py` file, the usage of the deprecated `np.float` is causing an `AttributeError`. As per the [NumPy 1.20 release notes](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), `np.float` is a deprecated alias for the built-in `float`.

### Steps to Reproduce Bug

```py
import ivy

x = 2.0
y = ivy.check_float(x)

print(y)

"""
(multienv) root ➜ /workspaces/ivy (main) $ /opt/miniconda/envs/multienv/bin/python3 /workspaces/ivy/useless.py
[2023-08-14 16:13:05,032] [ WARNING] xla_bridge.py:636 - No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/workspaces/ivy/ivy/utils/exceptions.py", line 345, in _handle_exceptions
    return fn(*args, **kwargs)
  File "/workspaces/ivy/ivy/functional/ivy/data_type.py", line 1958, in check_float
    return isinstance(x, (int, np.float)) and not type(x) == bool
  File "/opt/fw/mxnet/numpy/__init__.py", line 319, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/ivy/useless.py", line 31, in <module>
    y = ivy.check_float(z)
  File "/workspaces/ivy/ivy/utils/exceptions.py", line 372, in _handle_exceptions
    raise ivy.utils.exceptions.IvyAttributeError(
ivy.utils.exceptions.IvyAttributeError: numpy: check_float: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
"""
```

### Environment

Linux + VsCode + Docker

### Ivy Version

v1.1.9

### Backend

- [X] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

CPU

**Comment by akshatvishu** [comment]
This was fixed at <https://github.com/unifyai/ivy/commit/14ced24c9e9199c5eb3a71126505ba0d023ff8a9>
