### ISSUE TITLE
Fix Ivy Failing Test: torch - manipulation.reshape

### ISSUE THREAD

**Issue by sgalpha01** [unifyai/ivy#28017]
ToDo List: #27501 
Sub-Task in the "Priority Open" section

**Comment by sgalpha01** [comment]
To work with this error, `ivy/functional/backends/torch/manipulation.py` file should be targeted. Here is the log for running test:
```
❯ pytest ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py::test_reshape --verbose --backend torch
Use Database in ReadOnly Mode with local caching !
===================================================================== test session starts =====================================================================
platform linux -- Python 3.10.0, pytest-7.4.4, pluggy-1.3.0 -- /home/r0gue_shinobi/.miniconda3/envs/ivy_dev/bin/python3.10
cachedir: .pytest_cache
hypothesis profile 'ivy_profile' -> max_examples=25, print_blob=True, deadline=timedelta(milliseconds=500000), suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much, HealthCheck.data_too_large], database=MultiplexedDatabase(DirectoryBasedExampleDatabase(PosixPath('/home/r0gue_shinobi/Desktop/ivy/.hypothesis/examples')), ReadOnlyDatabase(RedisExampleDatabase(Redis<ConnectionPool<Connection<host=redis-17011.c259.us-central1-2.gce.cloud.redislabs.com,port=17011,db=0>>>, expire_after=datetime.timedelta(days=8))))
metadata: {'Python': '3.10.0', 'Platform': 'Linux-6.6.6-76060606-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.4.4', 'pluggy': '1.3.0'}, 'Plugins': {'anyio': '4.2.0', 'hypothesis': '6.96.1', 'metadata': '3.0.0', 'json-report': '1.5.0'}}
backend(s): torch
device: cpu
number of Hypothesis examples: 25
rootdir: /home/r0gue_shinobi/Desktop/ivy
plugins: anyio-4.2.0, hypothesis-6.96.1, metadata-3.0.0, json-report-1.5.0
collected 1 item                                                                                                                                              

ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py::test_reshape[cpu-torch-False-False] FAILED                                           [100%]

========================================================================== FAILURES ===========================================================================
_____________________________________________________________ test_reshape[cpu-torch-False-False] _____________________________________________________________
  + Exception Group Traceback (most recent call last):
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
  |     result: Optional[TResult] = func()
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/runner.py", line 262, in <lambda>
  |     lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
  |     return outcome.get_result()
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
  |     raise exc.with_traceback(exc.__traceback__)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
  |     raise e
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
  |     item.runtest()
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/python.py", line 1792, in runtest
  |     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
  |     result = testfunction(**testargs)
  |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/testing_helpers.py", line 449, in wrapped_test
  |     raise e
  |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/testing_helpers.py", line 442, in wrapped_test
  |     hypothesis_test_fn(*args, **kwargs)
  |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py", line 472, in test_reshape
  |     fn_tree="functional.ivy.reshape",
  |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/hypothesis/core.py", line 1597, in wrapped_test
  |     raise the_error_hypothesis_found
  | exceptiongroup.ExceptionGroup: Hypothesis found 4 distinct failures. (4 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py", line 497, in test_reshape
    |     helpers.test_function(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 561, in test_function
    |     ) = test_function_backend_computation(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 328, in test_function_backend_computation
    |     assert not np.may_share_memory(first_array, ret_)
    |   File "<__array_function__ internals>", line 200, in may_share_memory
    |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/torch/_tensor.py", line 1030, in __array__
    |     return self.numpy()
    | RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
    | Falsifying example: test_reshape(
    |     backend_fw='torch',
    |     on_device='cpu',
    |     dtype_value=(['bfloat16'], [array(-1, dtype=bfloat16)]),
    |     reshape=(),  # or any other generated value
    |     order='C',  # or any other generated value
    |     allowzero=False,  # or any other generated value
    |     test_flags=FunctionTestFlags(
    |         ground_truth_backend='tensorflow',
    |         num_positional_args=1,
    |         with_out=False,
    |         with_copy=True,
    |         instance_method=False,
    |         test_gradients=False,
    |         test_trace=False,
    |         transpile=False,
    |         as_variable=[True],
    |         native_arrays=[True],
    |         container=[False],
    |         precision_mode=False,
    |         test_cython_wrapper=False,
    |     ),
    |     fn_name='reshape',
    | )
    | Explanation:
    |     These lines were always and only run by failing examples:
    |         /home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/torch/_tensor.py:190
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.96.1', b'AXicY2QAAkYGCIDRDIxAFgAAXQAG') as a decorator on your test case
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py", line 497, in test_reshape
    |     helpers.test_function(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 561, in test_function
    |     ) = test_function_backend_computation(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 328, in test_function_backend_computation
    |     assert not np.may_share_memory(first_array, ret_)
    |   File "<__array_function__ internals>", line 200, in may_share_memory
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy/data_classes/array/array.py", line 375, in __array__
    |     return self._data.__array__(*args, dtype=self.dtype, **kwargs)
    |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/torch/_tensor.py", line 1032, in __array__
    |     return self.numpy().astype(dtype, copy=False)
    | RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
    | Falsifying example: test_reshape(
    |     backend_fw='torch',
    |     on_device='cpu',
    |     dtype_value=(['bfloat16'], [array(-1, dtype=bfloat16)]),
    |     reshape=(),  # or any other generated value
    |     order='C',  # or any other generated value
    |     allowzero=False,  # or any other generated value
    |     test_flags=FunctionTestFlags(
    |         ground_truth_backend='tensorflow',
    |         num_positional_args=1,
    |         with_out=False,
    |         with_copy=True,
    |         instance_method=False,
    |         test_gradients=False,
    |         test_trace=False,
    |         transpile=False,
    |         as_variable=[True],
    |         native_arrays=[False],
    |         container=[False],
    |         precision_mode=False,
    |         test_cython_wrapper=False,
    |     ),
    |     fn_name='reshape',
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.96.1', b'AXicY2QAAkYGCIDRYAYAAFoABQ==') as a decorator on your test case
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py", line 497, in test_reshape
    |     helpers.test_function(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 561, in test_function
    |     ) = test_function_backend_computation(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 328, in test_function_backend_computation
    |     assert not np.may_share_memory(first_array, ret_)
    |   File "<__array_function__ internals>", line 200, in may_share_memory
    |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/torch/_tensor.py", line 1030, in __array__
    |     return self.numpy()
    | TypeError: Got unsupported ScalarType BFloat16
    | Falsifying example: test_reshape(
    |     backend_fw='torch',
    |     on_device='cpu',
    |     dtype_value=(['bfloat16'], [array(-1, dtype=bfloat16)]),
    |     reshape=(),  # or any other generated value
    |     order='C',  # or any other generated value
    |     allowzero=False,  # or any other generated value
    |     test_flags=FunctionTestFlags(
    |         ground_truth_backend='tensorflow',
    |         num_positional_args=1,
    |         with_out=False,
    |         with_copy=True,
    |         instance_method=False,
    |         test_gradients=False,
    |         test_trace=False,
    |         transpile=False,
    |         as_variable=[False],
    |         native_arrays=[True],
    |         container=[False],
    |         precision_mode=False,
    |         test_cython_wrapper=False,
    |     ),
    |     fn_name='reshape',
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.96.1', b'AXicY2QAAkYGCIDRYBYAAFkABQ==') as a decorator on your test case
    +---------------- 4 ----------------
    | Traceback (most recent call last):
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py", line 497, in test_reshape
    |     helpers.test_function(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 561, in test_function
    |     ) = test_function_backend_computation(
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy_tests/test_ivy/helpers/function_testing.py", line 328, in test_function_backend_computation
    |     assert not np.may_share_memory(first_array, ret_)
    |   File "<__array_function__ internals>", line 200, in may_share_memory
    |   File "/home/r0gue_shinobi/Desktop/ivy/ivy/data_classes/array/array.py", line 375, in __array__
    |     return self._data.__array__(*args, dtype=self.dtype, **kwargs)
    |   File "/home/r0gue_shinobi/.miniconda3/envs/ivy_dev/lib/python3.10/site-packages/torch/_tensor.py", line 1032, in __array__
    |     return self.numpy().astype(dtype, copy=False)
    | TypeError: Got unsupported ScalarType BFloat16
    | Falsifying example: test_reshape(
    |     # The test sometimes passed when commented parts were varied together.
    |     backend_fw='torch',
    |     on_device='cpu',
    |     dtype_value=(['bfloat16'], [array(-1, dtype=bfloat16)]),
    |     reshape=(),  # or any other generated value
    |     order='C',  # or any other generated value
    |     allowzero=False,  # or any other generated value
    |     test_flags=FunctionTestFlags(
    |         ground_truth_backend='tensorflow',
    |         num_positional_args=1,
    |         with_out=False,
    |         with_copy=True,
    |         instance_method=False,
    |         test_gradients=False,
    |         test_trace=False,
    |         transpile=False,
    |         as_variable=[False],
    |         native_arrays=[False],
    |         container=[False],
    |         precision_mode=False,
    |         test_cython_wrapper=False,
    |     ),
    |     fn_name='reshape',
    | )
    | 
    | You can reproduce this example by temporarily adding @reproduce_failure('6.96.1', b'AXicY2QAAkYGCIDRYAAAAFYABA==') as a decorator on your test case
    +------------------------------------
====================================================================== warnings summary =======================================================================
ivy_tests/__init__.py:2
  /home/r0gue_shinobi/Desktop/ivy/ivy_tests/__init__.py:2: DeprecationWarning: Accessing jax.config via the jax.config submodule is deprecated.
    from jax.config import config

ivy/utils/exceptions.py:383
  /home/r0gue_shinobi/Desktop/ivy/ivy/utils/exceptions.py:383: UserWarning: The current backend: 'jax' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
    warnings.warn(

ivy/utils/exceptions.py:383
  /home/r0gue_shinobi/Desktop/ivy/ivy/utils/exceptions.py:383: UserWarning: The current backend: 'tensorflow' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
    warnings.warn(

ivy/utils/exceptions.py:383
  /home/r0gue_shinobi/Desktop/ivy/ivy/utils/exceptions.py:383: UserWarning: The current backend: 'paddle' does not support inplace updates natively. Ivy would quietly create new arrays when using inplace updates with this backend, leading to memory overhead (same applies for views). If you want to control your memory management, consider doing ivy.set_inplace_mode('strict') which should raise an error whenever an inplace update is attempted with this backend.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================= 0.0% of 1 passed ========================================================================================================================================= short test summary info ===================================================================
FAILED ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py::test_reshape[cpu-torch-False-False] - exceptiongroup.ExceptionGroup: Hypothesis found 4 distinct failures. (4 sub-exceptions)
========================================================== 1 failed, 4 warnings in 197.40s (0:03:17) ==========================================================
```

Notice that there are 4 distinct failures (of 2 types).

- TypeError: Got unsupported ScalarType BFloat16: It is expected as `numpy` doesn't support the dtype. So, it can be solved by using `@with_unsupported_dtypes({"2.6.0 and below": ("bfloat16, float16",)}, backend_version)
` decorator to let the test know about this.
- RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead: This error is more tricky. I'm getting it even after adding the decorator and for supported dtypes like `float32`, `float64` also.
