### ISSUE TITLE
[Bug]: Incorrect test handling when `with_copy=True`

### ISSUE THREAD

**Issue by sgalpha01** [unifyai/ivy#28036]
### Bug Explanation

Many sub-tasks in the "Priority Open" section are failing and they all have one common error:
`RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`

Now, this is not an issue with the actual function implementation, but the test suite. Whenever the `requires_grad` attribute is `True`, then this is bound to happen, as they are passed through `np.may_share_memory` without detaching from the computation graph. I'm not sure about other backends, but it is happening in `torch` backend for sure.

### Steps to Reproduce Bug

On running `pytest`, which requires `with_copy=True` with `torch` backend. 

For example,
`pytest ivy_tests/test_ivy/test_functional/test_core/test_manipulation.py::test_squeeze --backend torch --verbose`

### Environment

OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.6.6-76060606-generic
Environment: conda
Code Editor: VS Code
Python Version: 3.10.0

### Ivy Version

0.0.6.2

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [X] PyTorch
- [ ] JAX

### Device

CPU

**Comment by sgalpha01** [comment]
I have tried to address this issue in this PR: #28037 .

**Comment by sgalpha01** [comment]
I came across one more example with a different issue. I was working with issue #28041, and the error I was getting was: `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.`

So, I tried to replicate the issue:
```python
>>> import numpy as np
>>> import ivy
>>> a = ivy.array([0, 0, 0, 0])
>>> b = a.split(num_or_size_splits=[1, 1, 2], copy=True)
>>> a
ivy.array([0, 0, 0, 0])
>>> b
[ivy.array([0]), ivy.array([0]), ivy.array([0, 0])]
>>> np.may_share_memory(a, b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 200, in may_share_memory
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.
``` 

As you can see from the example, the `split` function is working as intended, but the test suite is failing.

**Comment by vedpatwardhan** [comment]
Hey @sgalpha01, thanks for the suggestion, feel free to create a PR making necessary fixes to the tests and request my review 👍
